export { default as Flag } from './Flag.svelte';
export { default as Github } from './Github.svelte';
export { default as Instagram } from './Instagram.svelte';
export { default as Linkedin } from './Linkedin.svelte';
export { default as Link } from './Link.svelte';
export { default as Menu } from './Menu.svelte';
export { default as Youtube } from './Youtube.svelte';
export { default as Return } from './Return.svelte';
export { default as Platzi } from './Platzi.svelte';
